clc;
clear;
n = 10000;
mu = [0;0];
sigma = [1 0.8; 0.8 1];A = chol(sigma, 'lower');
z = randn(2,n);
x = mu +A *z;
x = x' ;
sample_mean = mean(x);
sample_cov = cov(x);
scatter(x(:,1), x(:,2), 10, 'filled');
xlabel('X_1');
ylabel('X_2');
title('generated multivariate normal data');
grid on;